(function() {var implementors = {};
implementors['libc'] = [];implementors['bgfx'] = ["impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html' title='core::fmt::Debug'>Debug</a> for <a class='struct' href='bgfx/struct.StateFlags.html' title='bgfx::StateFlags'>StateFlags</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html' title='core::fmt::Debug'>Debug</a> for <a class='struct' href='bgfx/struct.BufferFlags.html' title='bgfx::BufferFlags'>BufferFlags</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html' title='core::fmt::Debug'>Debug</a> for <a class='struct' href='bgfx/struct.ClearFlags.html' title='bgfx::ClearFlags'>ClearFlags</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html' title='core::fmt::Debug'>Debug</a> for <a class='struct' href='bgfx/struct.DebugFlags.html' title='bgfx::DebugFlags'>DebugFlags</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html' title='core::fmt::Debug'>Debug</a> for <a class='struct' href='bgfx/struct.ResetFlags.html' title='bgfx::ResetFlags'>ResetFlags</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html' title='core::fmt::Debug'>Debug</a> for <a class='enum' href='bgfx/enum.RendererType.html' title='bgfx::RendererType'>RendererType</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html' title='core::fmt::Debug'>Debug</a> for <a class='enum' href='bgfx/enum.RenderFrame.html' title='bgfx::RenderFrame'>RenderFrame</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html' title='core::fmt::Debug'>Debug</a> for <a class='enum' href='bgfx/enum.Attrib.html' title='bgfx::Attrib'>Attrib</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html' title='core::fmt::Debug'>Debug</a> for <a class='enum' href='bgfx/enum.AttribType.html' title='bgfx::AttribType'>AttribType</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html' title='core::fmt::Debug'>Debug</a> for <a class='enum' href='bgfx/enum.BgfxError.html' title='bgfx::BgfxError'>BgfxError</a>",];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
